services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  # Spring Boot
  student-manager-backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: student-manager-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_HOST=mongodb
    depends_on:
      - mongodb

  # Angular
  student-manager-frontend:
    build:
      context: ./student-manager-frontend
      dockerfile: Dockerfile-frontend
    container_name: student-manager-frontend
    ports:
      - "80:80"
    depends_on:
      - student-manager-backend